apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth
  namespace: kube-system
data: 
  mapUsers: | 
    - rolearn: arn:aws:iam::742584907009:role/helloworld
      username: github-ci
      groups:
        - system: masters
