apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::742584907009:user/github-ci
      username: github-ci
      groups:
        - system: masters
