apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-image-deployment
  labels:
    app: hello-world-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-image
  template:
    metadata:
      labels:
        app: hello-world-image
    spec:
      containers:
      - name: hello-world-image
        image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/simplebank:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
