apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-image-deployment
  labels:
    app: hello-world-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-image
  template:
    metadata:
      labels:
        app: hello-world-image
    spec:
      containers:
      - name: hello-world-image-app
        image: 742584907009.dkr.ecr.us-west-1.amazonaws.com/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
