apiVersion: v1
kind: Service
metadata:
  name: hello-world-image-service
spec:
  selector:
    app: hello-world-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
